### ISSUE TITLE
Checkpoint 1 - Instructor Feedback

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [OscarJohnson6/IndieProject#1]
Hi @OscarJohnson6! What a great start with not only the checkpoint-required items, but a fair amount of code. 

Following are my observations and suggestions related to checkpoint 1, plus a very quick review of some of the code so far:

**Problem statement**

Does a good job laying out the problem and explaining how your application solves it. 

- [x] There are a lot of possible calculations/totals that your application could offer, and the problem statement reads that the application will offer all of them. It might be more accurate to list what exactly will be available in V1. 
- [x] Reminder to update the technology list as you go, such as the web service/s you are consuming. 

**User stories**

Your MVP user stories feel like they are right-sized for the semester while meeting the requirements of Ent Java - for example, full CRUD. 

- [x] "all health calculations " which calculations will be part of MVP? Should any be a stretch goal or V2?
- [x] To be thorough, there should probably be sign up, sign in, sign out stories. These will all be addressed with AWS Cognito (week 7)

**Project plan**

A good start for the first few weeks.

- [x] Some weeks are not accounted for, such as weeks 4, 5, 6. I recommend documenting when you will work on each user story, then write out the tasks in your plan for each story. 

**Screen design**

- [x] When comparing user stories to screens, I didn't see screens representing each story. I think you may have more work to do here?

**Reflection statements/Time Log**

Great work consistently tracking!

**Other**

- [x] You asked about package structure. I demo this in the week 4 and 5 with packages like: entity, persistence, controller, util. You do not have to use these, but I find they work well for me. 
- [x] I noticed some logs and property files which could contain information like usernames, passwords, etc. It would be a good idea to remove these from GitHub and add them to .gitignore. If you aren't able to find the details on how to do this, please post in slack as I'm sure others will run into this too!
- [x] Package names should be lowercase: https://github.com/OscarJohnson6/IndieProject/blob/c7a7b988766fd5bd540e8a250cf612e3f8cdedb1/src/main/java/Database/UserDao.java#L1. Uppercase generally indicates the name of a class.
- [x] It's great that you've already identified and started investigating apis/web services.  In week 8 you will learn how to call services and easily turn the responses into meaningful java classes/objects rather than a generic map. It might pay to check that out sooner than later. 
- [x] I know you are just getting started and testing thing out, but rather than hard-coding values like these, https://github.com/OscarJohnson6/IndieProject/blob/c7a7b988766fd5bd540e8a250cf612e3f8cdedb1/src/main/java/api/FitnessCalculator.java#L60-L61, use a property file for easy maintenance and so nobody "steals" your key. 
- [x] hibernate config file - I noticed a blank line at the top. I'm not sure if that could cause an issue. How does that file compare to a working example - did you follow along with the demo I did using the week 2 exercise? 
- [x] EntryDate - I think this would generally just be its own column on each table, and therefore an instance variable on each class that has an EntryDate column on the corresponding table.

**Comment by OscarJohnson6** [comment]
Hi @pawaitemadisoncollege sorry for not responding sooner I got sick the last few days. But I think I got most of the checklist done. I plan on looking into week 8's APIs this week.

- Created properties files for the API keys
- Clarified user stories more
- Renamed Database package, to database
- Used Date variable instead of object to EntryDate class
- Made a screen design combination
- Added the resources directory in test and main to .gitignore (but not fully sure if I did it right)

**Comment by pawaitemadisoncollege** [comment]
Hi @OscarJohnson6! Hope you are feeling better - there seems to be a lot of crud going around!

I'm not seeing those files w/ passwords, so I think your change did the trick!

Nice job with all the improvements: looks like very solid progress. The story board is a nice way to lay out the flow - well done! 

Looking forward to Checkpoint 2 this week!
